export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
export const NO_CURRENT_REFLECTION = "NO_CURRENT_REFLECTION";
export const REFLECTION_ALREADY_OPEN = "REFLECTION_ALREADY_OPEN";
export const NO_REFLECTION_OPEN = "NO_REFLECTION_OPEN";
