module.exports = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  NO_CURRENT_REFLECTION: "NO_CURRENT_REFLECTION",
  REFLECTION_ALREADY_OPEN: "REFLECTION_ALREADY_OPEN",
  NO_REFLECTION_OPEN: "NO_REFLECTION_OPEN",
};
